setwd("/Users/miawong/Desktop/Avigail_Data")
plutoold=read.csv("pluto_18v2_1.csv")
hviol=read.csv("Housing_Maintenance_Code_Violations2014.csv")
stable=read.csv("stabilized.csv")
plutoMN=read.csv("MN.csv")
plutoBX=read.csv("BX.csv")
plutoBK=read.csv("BK.csv")
plutoQN=read.csv("QN.csv")
plutoSI=read.csv("SI.csv")
pluto <- rbind(plutoBK,plutoBX,plutoMN,plutoQN,plutoSI)
